tasks:
  - init: npm install
    command: npm run test
  - name: Run Tests
    command: npx playwright test

env:
  LT_USERNAME: rizkafbrl
  LT_ACCESS_KEY: LT_GLnockZksen5Zx3dbi4qWMXbpGE0NCXAcCYEvPQpXvpDyxF
  